# Generated by Django 3.1.4 on 2021-10-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.ImageField(blank=True, upload_to='images')),
                ('session', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('payload', models.TextField(blank=True, max_length=1000, null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('dobBs', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('citizenshipID', models.CharField(max_length=10)),
                ('citizenshipNumber', models.CharField(max_length=30)),
                ('citizenshipDistrict', models.CharField(max_length=10)),
                ('witnessFirstname', models.CharField(max_length=50)),
                ('witnessMiddlename', models.CharField(blank=True, max_length=50)),
                ('witnessLastname', models.CharField(max_length=50)),
                ('relationtype', models.CharField(max_length=10)),
                ('permZone', models.CharField(max_length=20)),
                ('permDistrict', models.CharField(max_length=20)),
                ('permVillage', models.CharField(max_length=20)),
                ('permWardnumber', models.CharField(max_length=20)),
                ('permTole', models.CharField(max_length=20)),
                ('permMobilemumber', models.CharField(max_length=10)),
                ('presZone', models.CharField(max_length=20)),
                ('presDistrict', models.CharField(max_length=20)),
                ('presVillage', models.CharField(max_length=20)),
                ('presWardnumber', models.CharField(max_length=20)),
                ('presTole', models.CharField(max_length=20)),
                ('presMobilenumber', models.CharField(max_length=10)),
                ('cate', models.CharField(max_length=10)),
                ('zoneByAppliedZoneoffice', models.CharField(max_length=20)),
                ('licenseissueoffice', models.CharField(max_length=20)),
                ('captcha_text', models.CharField(blank=True, max_length=10, null=True)),
                ('session_text', models.CharField(blank=True, max_length=100, null=True)),
                ('client_added_at', models.DateTimeField(auto_now_add=True)),
                ('client_submitted_at', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
